package persistencia;
// Generated 11-01-2018 02:48:26 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Empresas generated by hbm2java
 */
public class Empresas  implements java.io.Serializable {


     private int idEmpresa;
     private String nombre;
     private String direccion;
     private int telefono;
     private String nit;
     private Integer numeroRegistro;
     private String giro;
     private Set ticketses = new HashSet(0);

    public Empresas() {
    }

	
    public Empresas(int idEmpresa, String nombre, String direccion, int telefono, String nit) {
        this.idEmpresa = idEmpresa;
        this.nombre = nombre;
        this.direccion = direccion;
        this.telefono = telefono;
        this.nit = nit;
    }
    public Empresas(int idEmpresa, String nombre, String direccion, int telefono, String nit, Integer numeroRegistro, String giro, Set ticketses) {
       this.idEmpresa = idEmpresa;
       this.nombre = nombre;
       this.direccion = direccion;
       this.telefono = telefono;
       this.nit = nit;
       this.numeroRegistro = numeroRegistro;
       this.giro = giro;
       this.ticketses = ticketses;
    }
   
    public int getIdEmpresa() {
        return this.idEmpresa;
    }
    
    public void setIdEmpresa(int idEmpresa) {
        this.idEmpresa = idEmpresa;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public int getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(int telefono) {
        this.telefono = telefono;
    }
    public String getNit() {
        return this.nit;
    }
    
    public void setNit(String nit) {
        this.nit = nit;
    }
    public Integer getNumeroRegistro() {
        return this.numeroRegistro;
    }
    
    public void setNumeroRegistro(Integer numeroRegistro) {
        this.numeroRegistro = numeroRegistro;
    }
    public String getGiro() {
        return this.giro;
    }
    
    public void setGiro(String giro) {
        this.giro = giro;
    }
    public Set getTicketses() {
        return this.ticketses;
    }
    
    public void setTicketses(Set ticketses) {
        this.ticketses = ticketses;
    }




}


