package persistencia;
// Generated 13-nov-2018 9:18:17 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Funciones generated by hbm2java
 */
public class Funciones  implements java.io.Serializable {


     private Integer idFuncion;
     private Horarios horarios;
     private Peliculas peliculas;
     private Precios precios;
     private String estado;
     private Set ventases = new HashSet(0);

    public Funciones() {
    }

	
    public Funciones(Horarios horarios, Peliculas peliculas, Precios precios) {
        this.horarios = horarios;
        this.peliculas = peliculas;
        this.precios = precios;
    }
    public Funciones(Horarios horarios, Peliculas peliculas, Precios precios, String estado, Set ventases) {
       this.horarios = horarios;
       this.peliculas = peliculas;
       this.precios = precios;
       this.estado = estado;
       this.ventases = ventases;
    }
   
    public Integer getIdFuncion() {
        return this.idFuncion;
    }
    
    public void setIdFuncion(Integer idFuncion) {
        this.idFuncion = idFuncion;
    }
    public Horarios getHorarios() {
        return this.horarios;
    }
    
    public void setHorarios(Horarios horarios) {
        this.horarios = horarios;
    }
    public Peliculas getPeliculas() {
        return this.peliculas;
    }
    
    public void setPeliculas(Peliculas peliculas) {
        this.peliculas = peliculas;
    }
    public Precios getPrecios() {
        return this.precios;
    }
    
    public void setPrecios(Precios precios) {
        this.precios = precios;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getVentases() {
        return this.ventases;
    }
    
    public void setVentases(Set ventases) {
        this.ventases = ventases;
    }




}


