package persistencia;
// Generated 11-01-2018 02:48:26 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Funciones generated by hbm2java
 */
public class Funciones  implements java.io.Serializable {


     private int idFuncion;
     private String horario;
     private Set ticketses = new HashSet(0);

    public Funciones() {
    }

	
    public Funciones(int idFuncion, String horario) {
        this.idFuncion = idFuncion;
        this.horario = horario;
    }
    public Funciones(int idFuncion, String horario, Set ticketses) {
       this.idFuncion = idFuncion;
       this.horario = horario;
       this.ticketses = ticketses;
    }
   
    public int getIdFuncion() {
        return this.idFuncion;
    }
    
    public void setIdFuncion(int idFuncion) {
        this.idFuncion = idFuncion;
    }
    public String getHorario() {
        return this.horario;
    }
    
    public void setHorario(String horario) {
        this.horario = horario;
    }
    public Set getTicketses() {
        return this.ticketses;
    }
    
    public void setTicketses(Set ticketses) {
        this.ticketses = ticketses;
    }




}


