package persistencia;
// Generated 11-01-2018 02:48:26 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Generos generated by hbm2java
 */
public class Generos  implements java.io.Serializable {


     private int idGenero;
     private String tipoGenero;
     private Set peliculases = new HashSet(0);

    public Generos() {
    }

	
    public Generos(int idGenero, String tipoGenero) {
        this.idGenero = idGenero;
        this.tipoGenero = tipoGenero;
    }
    public Generos(int idGenero, String tipoGenero, Set peliculases) {
       this.idGenero = idGenero;
       this.tipoGenero = tipoGenero;
       this.peliculases = peliculases;
    }
   
    public int getIdGenero() {
        return this.idGenero;
    }
    
    public void setIdGenero(int idGenero) {
        this.idGenero = idGenero;
    }
    public String getTipoGenero() {
        return this.tipoGenero;
    }
    
    public void setTipoGenero(String tipoGenero) {
        this.tipoGenero = tipoGenero;
    }
    public Set getPeliculases() {
        return this.peliculases;
    }
    
    public void setPeliculases(Set peliculases) {
        this.peliculases = peliculases;
    }




}


