package Persistencia;
// Generated 11-13-2018 10:57:41 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Horarios generated by hbm2java
 */
public class Horarios  implements java.io.Serializable {


     private Integer idHorario;
     private Salas salas;
     private String horario;
     private Set funcioneses = new HashSet(0);

    public Horarios() {
    }

	
    public Horarios(Salas salas, String horario) {
        this.salas = salas;
        this.horario = horario;
    }
    public Horarios(Salas salas, String horario, Set funcioneses) {
       this.salas = salas;
       this.horario = horario;
       this.funcioneses = funcioneses;
    }
   
    public Integer getIdHorario() {
        return this.idHorario;
    }
    
    public void setIdHorario(Integer idHorario) {
        this.idHorario = idHorario;
    }
    public Salas getSalas() {
        return this.salas;
    }
    
    public void setSalas(Salas salas) {
        this.salas = salas;
    }
    public String getHorario() {
        return this.horario;
    }
    
    public void setHorario(String horario) {
        this.horario = horario;
    }
    public Set getFuncioneses() {
        return this.funcioneses;
    }
    
    public void setFuncioneses(Set funcioneses) {
        this.funcioneses = funcioneses;
    }




}


