package persistencia;
// Generated 11-01-2018 02:48:26 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Precios generated by hbm2java
 */
public class Precios  implements java.io.Serializable {


     private int idPrecio;
     private String nombrePrecio;
     private Double valorPrecio;
     private Set ticketses = new HashSet(0);

    public Precios() {
    }

	
    public Precios(int idPrecio, String nombrePrecio) {
        this.idPrecio = idPrecio;
        this.nombrePrecio = nombrePrecio;
    }
    public Precios(int idPrecio, String nombrePrecio, Double valorPrecio, Set ticketses) {
       this.idPrecio = idPrecio;
       this.nombrePrecio = nombrePrecio;
       this.valorPrecio = valorPrecio;
       this.ticketses = ticketses;
    }
   
    public int getIdPrecio() {
        return this.idPrecio;
    }
    
    public void setIdPrecio(int idPrecio) {
        this.idPrecio = idPrecio;
    }
    public String getNombrePrecio() {
        return this.nombrePrecio;
    }
    
    public void setNombrePrecio(String nombrePrecio) {
        this.nombrePrecio = nombrePrecio;
    }
    public Double getValorPrecio() {
        return this.valorPrecio;
    }
    
    public void setValorPrecio(Double valorPrecio) {
        this.valorPrecio = valorPrecio;
    }
    public Set getTicketses() {
        return this.ticketses;
    }
    
    public void setTicketses(Set ticketses) {
        this.ticketses = ticketses;
    }




}


