package Persistencia;
// Generated 11-13-2018 10:57:41 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Salas generated by hbm2java
 */
public class Salas  implements java.io.Serializable {


     private Integer idSala;
     private Sucursales sucursales;
     private Integer numeroSala;
     private String tipoSala;
     private Set horarioses = new HashSet(0);

    public Salas() {
    }

	
    public Salas(Sucursales sucursales) {
        this.sucursales = sucursales;
    }
    public Salas(Sucursales sucursales, Integer numeroSala, String tipoSala, Set horarioses) {
       this.sucursales = sucursales;
       this.numeroSala = numeroSala;
       this.tipoSala = tipoSala;
       this.horarioses = horarioses;
    }
   
    public Integer getIdSala() {
        return this.idSala;
    }
    
    public void setIdSala(Integer idSala) {
        this.idSala = idSala;
    }
    public Sucursales getSucursales() {
        return this.sucursales;
    }
    
    public void setSucursales(Sucursales sucursales) {
        this.sucursales = sucursales;
    }
    public Integer getNumeroSala() {
        return this.numeroSala;
    }
    
    public void setNumeroSala(Integer numeroSala) {
        this.numeroSala = numeroSala;
    }
    public String getTipoSala() {
        return this.tipoSala;
    }
    
    public void setTipoSala(String tipoSala) {
        this.tipoSala = tipoSala;
    }
    public Set getHorarioses() {
        return this.horarioses;
    }
    
    public void setHorarioses(Set horarioses) {
        this.horarioses = horarioses;
    }




}


