package persistencia;
// Generated 11-01-2018 02:48:26 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Salas generated by hbm2java
 */
public class Salas  implements java.io.Serializable {


     private int idSala;
     private String numeroSala;
     private String tipoSala;
     private Set ticketses = new HashSet(0);

    public Salas() {
    }

	
    public Salas(int idSala, String numeroSala, String tipoSala) {
        this.idSala = idSala;
        this.numeroSala = numeroSala;
        this.tipoSala = tipoSala;
    }
    public Salas(int idSala, String numeroSala, String tipoSala, Set ticketses) {
       this.idSala = idSala;
       this.numeroSala = numeroSala;
       this.tipoSala = tipoSala;
       this.ticketses = ticketses;
    }
   
    public int getIdSala() {
        return this.idSala;
    }
    
    public void setIdSala(int idSala) {
        this.idSala = idSala;
    }
    public String getNumeroSala() {
        return this.numeroSala;
    }
    
    public void setNumeroSala(String numeroSala) {
        this.numeroSala = numeroSala;
    }
    public String getTipoSala() {
        return this.tipoSala;
    }
    
    public void setTipoSala(String tipoSala) {
        this.tipoSala = tipoSala;
    }
    public Set getTicketses() {
        return this.ticketses;
    }
    
    public void setTicketses(Set ticketses) {
        this.ticketses = ticketses;
    }




}


