package persistencia;
// Generated 11-01-2018 02:48:26 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sucursales generated by hbm2java
 */
public class Sucursales  implements java.io.Serializable {


     private int idSucursal;
     private String nombreSucursal;
     private String direccionSucursal;
     private int telefono;
     private Set ticketses = new HashSet(0);

    public Sucursales() {
    }

	
    public Sucursales(int idSucursal, String nombreSucursal, String direccionSucursal, int telefono) {
        this.idSucursal = idSucursal;
        this.nombreSucursal = nombreSucursal;
        this.direccionSucursal = direccionSucursal;
        this.telefono = telefono;
    }
    public Sucursales(int idSucursal, String nombreSucursal, String direccionSucursal, int telefono, Set ticketses) {
       this.idSucursal = idSucursal;
       this.nombreSucursal = nombreSucursal;
       this.direccionSucursal = direccionSucursal;
       this.telefono = telefono;
       this.ticketses = ticketses;
    }
   
    public int getIdSucursal() {
        return this.idSucursal;
    }
    
    public void setIdSucursal(int idSucursal) {
        this.idSucursal = idSucursal;
    }
    public String getNombreSucursal() {
        return this.nombreSucursal;
    }
    
    public void setNombreSucursal(String nombreSucursal) {
        this.nombreSucursal = nombreSucursal;
    }
    public String getDireccionSucursal() {
        return this.direccionSucursal;
    }
    
    public void setDireccionSucursal(String direccionSucursal) {
        this.direccionSucursal = direccionSucursal;
    }
    public int getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(int telefono) {
        this.telefono = telefono;
    }
    public Set getTicketses() {
        return this.ticketses;
    }
    
    public void setTicketses(Set ticketses) {
        this.ticketses = ticketses;
    }




}


