package persistencia;
// Generated 11-01-2018 02:48:26 PM by Hibernate Tools 4.3.1



/**
 * Tickets generated by hbm2java
 */
public class Tickets  implements java.io.Serializable {


     private int idTicket;
     private Empresas empresas;
     private Funciones funciones;
     private Peliculas peliculas;
     private Precios precios;
     private Salas salas;
     private Sucursales sucursales;
     private Usuarios usuarios;
     private int cantidadEntradas;
     private double totalTicket;
     private String fecha;

    public Tickets() {
    }

    public Tickets(int idTicket, Empresas empresas, Funciones funciones, Peliculas peliculas, Precios precios, Salas salas, Sucursales sucursales, Usuarios usuarios, int cantidadEntradas, double totalTicket, String fecha) {
       this.idTicket = idTicket;
       this.empresas = empresas;
       this.funciones = funciones;
       this.peliculas = peliculas;
       this.precios = precios;
       this.salas = salas;
       this.sucursales = sucursales;
       this.usuarios = usuarios;
       this.cantidadEntradas = cantidadEntradas;
       this.totalTicket = totalTicket;
       this.fecha = fecha;
    }
   
    public int getIdTicket() {
        return this.idTicket;
    }
    
    public void setIdTicket(int idTicket) {
        this.idTicket = idTicket;
    }
    public Empresas getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Empresas empresas) {
        this.empresas = empresas;
    }
    public Funciones getFunciones() {
        return this.funciones;
    }
    
    public void setFunciones(Funciones funciones) {
        this.funciones = funciones;
    }
    public Peliculas getPeliculas() {
        return this.peliculas;
    }
    
    public void setPeliculas(Peliculas peliculas) {
        this.peliculas = peliculas;
    }
    public Precios getPrecios() {
        return this.precios;
    }
    
    public void setPrecios(Precios precios) {
        this.precios = precios;
    }
    public Salas getSalas() {
        return this.salas;
    }
    
    public void setSalas(Salas salas) {
        this.salas = salas;
    }
    public Sucursales getSucursales() {
        return this.sucursales;
    }
    
    public void setSucursales(Sucursales sucursales) {
        this.sucursales = sucursales;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public int getCantidadEntradas() {
        return this.cantidadEntradas;
    }
    
    public void setCantidadEntradas(int cantidadEntradas) {
        this.cantidadEntradas = cantidadEntradas;
    }
    public double getTotalTicket() {
        return this.totalTicket;
    }
    
    public void setTotalTicket(double totalTicket) {
        this.totalTicket = totalTicket;
    }
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }




}


