package persistencia;
// Generated 13-nov-2018 9:21:38 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TiposUsuarios generated by hbm2java
 */
public class TiposUsuarios  implements java.io.Serializable {


     private Integer idTipoUsuario;
     private String tipo;
     private Set usuarioses = new HashSet(0);

    public TiposUsuarios() {
    }

    public TiposUsuarios(String tipo, Set usuarioses) {
       this.tipo = tipo;
       this.usuarioses = usuarioses;
    }
   
    public Integer getIdTipoUsuario() {
        return this.idTipoUsuario;
    }
    
    public void setIdTipoUsuario(Integer idTipoUsuario) {
        this.idTipoUsuario = idTipoUsuario;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Set getUsuarioses() {
        return this.usuarioses;
    }
    
    public void setUsuarioses(Set usuarioses) {
        this.usuarioses = usuarioses;
    }




}


