package persistencia;
// Generated 11-01-2018 02:48:26 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TiposUsuarios generated by hbm2java
 */
public class TiposUsuarios  implements java.io.Serializable {


     private int idTipoUsuario;
     private String tipo;
     private Set usuarioses = new HashSet(0);

    public TiposUsuarios() {
    }

	
    public TiposUsuarios(int idTipoUsuario, String tipo) {
        this.idTipoUsuario = idTipoUsuario;
        this.tipo = tipo;
    }
    public TiposUsuarios(int idTipoUsuario, String tipo, Set usuarioses) {
       this.idTipoUsuario = idTipoUsuario;
       this.tipo = tipo;
       this.usuarioses = usuarioses;
    }
   
    public int getIdTipoUsuario() {
        return this.idTipoUsuario;
    }
    
    public void setIdTipoUsuario(int idTipoUsuario) {
        this.idTipoUsuario = idTipoUsuario;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Set getUsuarioses() {
        return this.usuarioses;
    }
    
    public void setUsuarioses(Set usuarioses) {
        this.usuarioses = usuarioses;
    }




}


