package persistencia;
// Generated 11-01-2018 02:48:26 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private int idUsuario;
     private TiposUsuarios tiposUsuarios;
     private String nickname;
     private String nombres;
     private String apellidos;
     private String correo;
     private Set ticketses = new HashSet(0);

    public Usuarios() {
    }

	
    public Usuarios(int idUsuario, TiposUsuarios tiposUsuarios, String nickname, String nombres, String apellidos, String correo) {
        this.idUsuario = idUsuario;
        this.tiposUsuarios = tiposUsuarios;
        this.nickname = nickname;
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.correo = correo;
    }
    public Usuarios(int idUsuario, TiposUsuarios tiposUsuarios, String nickname, String nombres, String apellidos, String correo, Set ticketses) {
       this.idUsuario = idUsuario;
       this.tiposUsuarios = tiposUsuarios;
       this.nickname = nickname;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.correo = correo;
       this.ticketses = ticketses;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public TiposUsuarios getTiposUsuarios() {
        return this.tiposUsuarios;
    }
    
    public void setTiposUsuarios(TiposUsuarios tiposUsuarios) {
        this.tiposUsuarios = tiposUsuarios;
    }
    public String getNickname() {
        return this.nickname;
    }
    
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public Set getTicketses() {
        return this.ticketses;
    }
    
    public void setTicketses(Set ticketses) {
        this.ticketses = ticketses;
    }




}


