package Persistencia;
// Generated 11-12-2018 11:20:36 AM by Hibernate Tools 4.3.1



/**
 * Ventas generated by hbm2java
 */
public class Ventas  implements java.io.Serializable {


     private Integer idVenta;
     private Funciones funciones;
     private String fechaVenta;
     private String nombreCliente;
     private String dui;
     private Double total;
     private String estado;

    public Ventas() {
    }

	
    public Ventas(Funciones funciones) {
        this.funciones = funciones;
    }
    public Ventas(Funciones funciones, String fechaVenta, String nombreCliente, String dui, Double total, String estado) {
       this.funciones = funciones;
       this.fechaVenta = fechaVenta;
       this.nombreCliente = nombreCliente;
       this.dui = dui;
       this.total = total;
       this.estado = estado;
    }
   
    public Integer getIdVenta() {
        return this.idVenta;
    }
    
    public void setIdVenta(Integer idVenta) {
        this.idVenta = idVenta;
    }
    public Funciones getFunciones() {
        return this.funciones;
    }
    
    public void setFunciones(Funciones funciones) {
        this.funciones = funciones;
    }
    public String getFechaVenta() {
        return this.fechaVenta;
    }
    
    public void setFechaVenta(String fechaVenta) {
        this.fechaVenta = fechaVenta;
    }
    public String getNombreCliente() {
        return this.nombreCliente;
    }
    
    public void setNombreCliente(String nombreCliente) {
        this.nombreCliente = nombreCliente;
    }
    public String getDui() {
        return this.dui;
    }
    
    public void setDui(String dui) {
        this.dui = dui;
    }
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


